# Generated by Django 5.0.1 on 2024-01-21 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dir', models.CharField(max_length=200)),
                ('tel', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Gymbro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.IntegerField()),
                ('dir', models.CharField(max_length=200)),
                ('tel', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('os', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym_admin.gym')),
            ],
        ),
        migrations.CreateModel(
            name='GymbroporTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gymbro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_admin.gymbro')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_admin.turno')),
            ],
        ),
    ]
