# Generated by Django 5.0.1 on 2024-01-21 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_admin', '0002_turno_turno_alter_gym_tel_alter_gymbro_dni_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrenamiento', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rutina', models.CharField(blank=True, default='', max_length=100)),
                ('repeticiones', models.IntegerField()),
                ('series', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='gymbroporturno',
            name='entrenamiento',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gym_admin.entrenamiento'),
        ),
        migrations.AddField(
            model_name='gymbroporturno',
            name='rutina',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gym_admin.rutina'),
        ),
    ]
