# Generated by Django 5.0.1 on 2024-01-21 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_admin', '0003_entrenamiento_rutina_gymbroporturno_entrenamiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='rutina',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym_admin.plan'),
        ),
    ]
