# Generated by Django 5.0.1 on 2024-01-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_admin', '0004_plan_rutina_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan',
            field=models.CharField(max_length=14),
        ),
    ]
