# Generated by Django 5.0.1 on 2024-01-21 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_admin', '0005_alter_plan_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymbroporturno',
            name='rutina',
        ),
        migrations.AddField(
            model_name='gymbroporturno',
            name='plan',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gym_admin.plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan',
            field=models.CharField(max_length=20),
        ),
    ]
