# Generated by Django 5.0.1 on 2024-01-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_admin', '0007_remove_gymbroporturno_plan_gymbroporturno_rutina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymbroporturno',
            name='entrenamiento',
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='descripcion',
            field=models.TextField(default='Ingrese descripción'),
        ),
        migrations.AddField(
            model_name='rutina',
            name='ejercicios',
            field=models.ManyToManyField(to='gym_admin.entrenamiento'),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='entrenamiento',
            field=models.CharField(max_length=100),
        ),
    ]
