# Generated by Django 5.0.1 on 2024-01-21 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_admin', '0008_remove_gymbroporturno_entrenamiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymbroporturno',
            name='rutina',
        ),
        migrations.RemoveField(
            model_name='rutina',
            name='ejercicios',
        ),
        migrations.AddField(
            model_name='gymbroporturno',
            name='entrenamiento',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gym_admin.entrenamiento'),
        ),
        migrations.AddField(
            model_name='gymbroporturno',
            name='plan',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gym_admin.plan'),
        ),
    ]
