# Generated by Django 5.0.1 on 2024-01-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_admin', '0009_remove_gymbroporturno_rutina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymbro',
            name='fecha_nac',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gymbro',
            name='inicio_act',
            field=models.DateField(blank=True, null=True),
        ),
    ]
