# Generated by Django 5.0.1 on 2024-01-23 13:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_admin', '0010_gymbro_fecha_nac_gymbro_inicio_act'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymbro',
            name='inicio_act',
            field=models.DateField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de inicio de actividad'),
        ),
        migrations.AlterField(
            model_name='gymbro',
            name='os',
            field=models.CharField(max_length=100, verbose_name='Obra Social'),
        ),
    ]
