# Generated by Django 5.0.1 on 2024-01-25 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_admin', '0011_alter_gymbro_inicio_act_alter_gymbro_os'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymbroporturno',
            name='plan',
        ),
        migrations.AddField(
            model_name='gymbroporturno',
            name='rutina',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gym_admin.rutina'),
        ),
    ]
