# Generated by Django 5.0.1 on 2024-01-25 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_admin', '0013_remove_rutina_plan_remove_rutina_repeticiones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymbro',
            name='addinfo',
        ),
        migrations.RemoveField(
            model_name='gymbroporturno',
            name='plan',
        ),
        migrations.AddField(
            model_name='rutina',
            name='plan',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gym_admin.plan'),
        ),
        migrations.AddField(
            model_name='rutina',
            name='repeticiones',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rutina',
            name='series',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='rutina',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
